# NumPy

## Exercícios

### Exercício 1)
Utilize comprehension para gerar a lista de todos os números interios entre 0 e 19. Converta a lista em um <font color='blue'>numpy</font> array bidimensional (matriz) com 4 linhas e 5 colunas.

In [ ]:
import numpy as np

In [ ]:
numeros_list = [num for num in range(20)] # Cria a lista usando list comprehension
numeros_arr = np.array(numeros_list)      # Converte para um numpy array
numeros_arr = numeros_arr.reshape((4, 5)) # Redimensiona para 4 linhas e 5 colunas
numeros_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Exercício 2)
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [ ]:
arr = np.random.randint(0, 21, 30) # Cria um array com números aleatórios
A = arr.reshape((5, 6))            # Redimensiona para 5 linhas e 6 colunas
A

array([[13,  7,  0, 20,  7, 14],
       [11,  4,  6, 12, 12, 13],
       [ 2, 17, 16, 10,  1,  1],
       [ 9,  4,  1,  1, 13, 15],
       [ 2, 17,  2, 11,  3,  0]])

### Exercício 3)
Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [ ]:
arr = A.copy()
arr

array([[13,  7,  0, 20,  7, 14],
       [11,  4,  6, 12, 12, 13],
       [ 2, 17, 16, 10,  1,  1],
       [ 9,  4,  1,  1, 13, 15],
       [ 2, 17,  2, 11,  3,  0]])

In [ ]:
arr1 = A.copy()
arr1 = arr[[0, 1, 3]]
arr1

array([[13,  7,  0, 20,  7, 14],
       [11,  4,  6, 12, 12, 13],
       [ 9,  4,  1,  1, 13, 15]])

In [ ]:
arr2 = A.copy()
arr2 = arr2[[1, 2]][:, [0, 2, 4]]
arr2

array([[11,  6, 12],
       [ 2, 16,  1]])

In [ ]:
arr3 = A.copy()
arr3 = arr3[[1, 3]][:, [1, 3]]
arr3

array([[ 4, 12],
       [ 4,  1]])

### Exercício 4)
Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20.
- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1

__Dica:__ Gere máscaras booleanas para realizar as modificações nos arrays.

In [ ]:
A = np.random.randint(0, 20, 30)
A = A.reshape((5, 6))
A

array([[ 0, 17,  2,  0, 14,  4],
       [16,  5,  0, 14, 12,  6],
       [18, 11, 15,  6,  1,  4],
       [ 3,  1,  5, 14,  7,  6],
       [ 1, 14,  2,  5,  1, 19]])

In [ ]:
Ac = A.copy()

In [ ]:
mask_A = A > 10
A[mask_A] = -1
A

array([[ 0, -1,  2,  0, -1,  4],
       [-1,  5,  0, -1, -1,  6],
       [-1, -1, -1,  6,  1,  4],
       [ 3,  1,  5, -1,  7,  6],
       [ 1, -1,  2,  5,  1, -1]])

In [ ]:
mask_Ac = (7 < Ac) & (Ac < 15)
Ac[mask_Ac] = -1
Ac

array([[ 0, 17,  2,  0, -1,  4],
       [16,  5,  0, -1, -1,  6],
       [18, -1, 15,  6,  1,  4],
       [ 3,  1,  5, -1,  7,  6],
       [ 1, -1,  2,  5,  1, 19]])

### Exercício 5)
Construa um array `A` com 20 linhas e 10 colunas onde os elementos são os números interios de  1 até 200.
- Crie uma __view__ de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par.
- Crie uma __view__ de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar.

In [ ]:
A = np.arange(1, 201)
A = A.reshape(20, 10)
A

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170

In [ ]:
A_lpares = A.copy()
A_lpares = A_lpares[np.arange(0, A_lpares.shape[0], 2)] # Linhas pares
A_lpares

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170],
       [181, 182, 183, 184, 185, 186, 187, 188, 189, 190]])

In [ ]:
A_lpares_cimpares = A.copy()
#                                                  linhas pares                                   colunas ímpares
A_lpares_cimpares = A_lpares_cimpares[np.arange(0, A_lpares_cimpares.shape[0], 2)][:,np.arange(1, A_lpares_cimpares.shape[1], 2)]
A_lpares_cimpares

array([[  2,   4,   6,   8,  10],
       [ 22,  24,  26,  28,  30],
       [ 42,  44,  46,  48,  50],
       [ 62,  64,  66,  68,  70],
       [ 82,  84,  86,  88,  90],
       [102, 104, 106, 108, 110],
       [122, 124, 126, 128, 130],
       [142, 144, 146, 148, 150],
       [162, 164, 166, 168, 170],
       [182, 184, 186, 188, 190]])

### Exercício 6)
Substitua os elementos do array `A` do exercício anterior por -1 quando pelo menos um dos índices do elemento é par.

__Dica:__ Construa uma máscara booleana

In [ ]:
mask = [[(i%2==0)or(j%2==0) for j in range(A.shape[1])] for i in range(A.shape[0])]
mask

[[True, True, True, True, True, True, True, True, True, True],
 [True, False, True, False, True, False, True, False, True, False],
 [True, True, True, True, True, True, True, True, True, True],
 [True, False, True, False, True, False, True, False, True, False],
 [True, True, True, True, True, True, True, True, True, True],
 [True, False, True, False, True, False, True, False, True, False],
 [True, True, True, True, True, True, True, True, True, True],
 [True, False, True, False, True, False, True, False, True, False],
 [True, True, True, True, True, True, True, True, True, True],
 [True, False, True, False, True, False, True, False, True, False],
 [True, True, True, True, True, True, True, True, True, True],
 [True, False, True, False, True, False, True, False, True, False],
 [True, True, True, True, True, True, True, True, True, True],
 [True, False, True, False, True, False, True, False, True, False],
 [True, True, True, True, True, True, True, True, True, True],
 [True, False, True,

In [ ]:
A[mask] = -1
A

array([[ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  12,  -1,  14,  -1,  16,  -1,  18,  -1,  20],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  32,  -1,  34,  -1,  36,  -1,  38,  -1,  40],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  52,  -1,  54,  -1,  56,  -1,  58,  -1,  60],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  72,  -1,  74,  -1,  76,  -1,  78,  -1,  80],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  92,  -1,  94,  -1,  96,  -1,  98,  -1, 100],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1, 112,  -1, 114,  -1, 116,  -1, 118,  -1, 120],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1, 132,  -1, 134,  -1, 136,  -1, 138,  -1, 140],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1, 152,  -1, 154,  -1, 156,  -1, 158,  -1, 160],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1

### Exercício 7)
Construa uma função chamada `ordena_linhas` que recebe uma matriz como parâmetro e troque as linhas de posição para que fiquem ordenadas de acordo com a primeira coluna. Por exemplo:
```python
A = np.array([[20, 26, 12],
              [8, 3, 26],
              [3, 10, 4]])
print(ordena_linhas(A))
```
deve resultar em
```python
[[ 3 10  4]
 [ 8  3 26]
 [20 26 12]]
```

In [ ]:
def ordena_linhas(matx:np.array) -> np.array:
  '''
  Recebe uma Matriz bidimensional matx e
  a ordena usando o algoritmo bubble sort.
  Sendo o índice o elemento da primeira
  coluna de cada linha.
  '''
  for i in range(matx.shape[0]):
    for j in range(i, matx.shape[1]):
      if matx[i][0] > matx[j][0]:
        temp = matx[i][0]
        matx[i][0] = matx[j][0]
        matx[j][0] = temp

  return matx

In [ ]:
matx = np.array([[20, 26, 12],
                 [ 8,  3, 26],
                 [ 3,  10, 4]])
ordena_linhas(matx)

array([[ 3, 26, 12],
       [ 8,  3, 26],
       [20, 10,  4]])

## Links, Artigos e Referências:

- [Documentação do Numpy](https://numpy.org/doc/), documentação onde vocês podem encontrar mais informações sobre os métodos e funções do NumPy e descobrir novos métodos que não foram apresentados no curso;
- ["5 Smart Numpy Functions",](https://towardsdatascience.com/5-smart-python-numpy-functions-dfd1072d2cb4) artigo escrito pelo Towards Data Science;
- ["Writing beautiful code with NumPy"](https://medium.com/@zachary.bedell/writing-beautiful-code-with-numpy-505f3b353174), artigo escrito por Zach Bedell;