# Lista 1 - NumPy

## Exercícios

Para a resolução dos exercícios abaixo, utilize todas as ferramentas e métodos do NumPy aprendidos em aula e existe algumas outras métodos que podem ser úteis na documentação [_NumPy Documentation_](https://numpy.org/doc/). Durante a correção, não será considerado exercícios que não utilizar a ferramenta (muitos deles da pra responder apenas com Python, mas não é esse o intuito da lista).

__Funcionamento dos Exercícios:__ todos os exercícios são do estilo onde será preciso criar uma função para resolver a proposta do enunciado. Será avaliado apenas a função, mas sugiro que crie casos de testes para avaliar se a função está operando corretamente.

__Avaliação e Entrega:__ São 5 exercícios que valem 10 pontos, e a entrega vai ser na forma de um notebook através da tarefa criada no LMS.

__Data Limite para Entrega:__ Próxima aula 19/02


### 1) Restaurantes Mais Próximos

Perto da casa de João existem vários restaurantes que entregam comida e João deseja fazer um pedido, mas ele tem um compromisso marcado e não pode esperar muito tempo. Então João quer saber qual é o restaurante mais próximo da residencial dele utilizando da distância Euclidiana, cuja a fórmula é dado pela equação a seguir:

<img align="center" src="https://i.upmath.me/svg/%20d(A%2C%20B)%20%3D%20%5Csqrt%7B(x_%7BA%2C%201%7D%20-%20x_%7BB%2C%201%7D)%5E%7B2%7D%20%2B%20(x_%7BA%2C%202%7D%20-%20x_%7BB%2C%202%7D)%5E%7B2%7D%20%2B%20...%20%2B%20(x_%7BA%2C%20n%7D%20-%20x_%7BB%2C%20n%7D)%5E%7B2%7D%7D" alt=" d(A, B) = \sqrt{(x_{A, 1} - x_{B, 1})^{2} + (x_{A, 2} - x_{B, 2})^{2} + ... + (x_{A, n} - x_{B, n})^{2}}" />

Desenvolva uma função chamada `restaurante_mais_proximo` que irá receber como parâmetros respectivamente __uma lista de coordenadas da casa do João__ e __uma lista com 4 listas com as coordenadas dos restaurantes a verificar__ e o retorno da função deve ser __o número referente ao restaurante mais próximo__. Importante ressaltar que o número do restaurante começa pelo 1 e que em caso de empate, deve-se indicar __o primeiro restaurante a apresentar a menor distância__.

In [ ]:
import numpy as np

In [ ]:
def restaurantes_mais_proximos(casa:list[float], restaurantes:list[list[float]]) -> int:
  '''
  Retorna uma lista com as coordenadas da casa e uma lista
  com as coordenadas de n restaurantes e retorna o índice(começando em 1)
  do restaurante com a menor distância.
  '''
  # Converte as variáveis para arrays
  casa = np.array(casa)
  restaurantes = np.array(restaurantes)
  # Calcula as distâncias
  #           yi = (Xai - Xbi)²
  dists = (casa-restaurantes)**2
  #                    √(sum(yi))
  dists = np.array([(row.sum())**0.5 for row in dists])
  # Encontra o índice do menos distante
  menor_dist = dists.min()
  for i,dist in enumerate(dists, start=1):
    if dist == menor_dist:
      # Retorna o índice do primeiro encontrado
      return i

In [ ]:
# Exemplo 1
restaurantes = [[1, 3, 5], [2, 4, 0], [3, 3, 3], [1, 6, 6]]
joao = [0, 1, 2]
# Resultado = 1
restaurantes_mais_proximos(joao, restaurantes)

1

In [ ]:
# Exemplo 2
restaurantes = [
       [0.86617615, 0.60111501, 0.70807258, 0.02058449, 0.96990985, 0.83244264, 0.21233911],
       [0.18182497, 0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914, 0.61185289],
       [0.13949386, 0.29214465, 0.36636184, 0.45606998, 0.78517596, 0.19967378, 0.51423444],
       [0.59241457, 0.04645041, 0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203]]
joao = [0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864, 0.15599452, 0.05808361]
# Resultado = 2
print(restaurantes_mais_proximos(joao, restaurantes))

2


## 2) Ordenando pelo MMC

O Mínimo Múltiplo Comum (MMC) de dois ou mais números é definido pelo múltiplo comum corresponde a todos os números observados. Por exemplo o MMC entre 6 e 10 é o 30 devido aos número 2, 3 e 5. O objetivo deste exercício, além de calcular o MMC será ordenar a lista utilizando o MMC. Portanto desenvolva a função `ordenar_mmc` onde como entrada irá receber uma lista de números e um número a parte de referência. A função deve calcular O MMC de cada um dos números da lista em relação ao de referência e em seguida ordenar os números originais de acordo com o MMC do menor valor para o maior, como o exemplo a seguir:

```python
# lista de entrada
lista = [12, 8, 10]

# numero de referência
ref = 4

# utilizando a função
print(ordenar_mmc(lista, ref))

# Resultado da função, pois o mmcs = [12, 8, 20]
[8, 12, 10]
```

In [ ]:
ordenar_pelo_mmc([12, 8, 10], 4)

array([ 8, 12, 10])

In [ ]:
def ordenar_mmc(numeros:list[int], num_ref:int) -> np.array:
  '''
  Retorna um array que é uma permutação da lista
  'numeros' recebida, sendo esta lista ordenada pelo
  mmc entre cada item e o 'num_ref'.
  '''
  # Converte a lista para um array
  numeros = np.array(numeros)
  # Usa a função map para criar uma lista com os mmcs
  mmcs_map = map(calcula_mmc, numeros, [num_ref]*len(numeros))
  mmcs_list = list(mmcs_map)
  # COnverte a lista de mmcs para array
  mmcs_array = np.array(mmcs_list)
  # Guarda os índices da ordenação
  indices = np.argsort(mmcs_array)
  # Usa os índices para ordenar o array de números
  sorted_nums = numeros[indices]

  return sorted_nums

In [ ]:
def calcula_mmc(num1, num2):
  mmc = 1
  for i in range(2, max(num1, num2)+1):
    while num1%i==0 or num2%i==0:
      if num1%i==0 and num2%i==0:
        num1 /= i
        num2 /= i
      elif num1%i==0:
        num1 /= i
      else:
        num2 /= i
      mmc *= i
  return mmc

In [ ]:
#Exemplos
# Exemplo 1
lista = [12, 20, 14, 25, 100, 50, 23]
ref = 5
# Resposta
#[20, 25, 50, 12, 14, 100, 23]
print(ordenar_mmc(lista, ref))

[ 20  25  50  12  14 100  23]


In [ ]:
# Exemplo 2
lista = [7, 16, 22, 81, 9, 42, 11, 2]
ref = 8
# Resposta
#[2, 16, 7, 9, 22, 11, 42, 81]
print(ordenar_mmc(lista, ref))

[ 2 16  7  9 22 11 42 81]


### 3) Normalização ou Z-Score

A normalização (também conhecido como Z-Score) é uma ferramenta muito importante da estatística onde para um conjunto de dados, calcula-se quais serão os respectivos valores se aquele conjunto de dados seguir uma dstribuição normal. O objetivo deste exercício será desenvolver a função `z_score`, onde dado uma lista de entrada com um conjunto de dados quaisquer, devolve a lista com os respectivos Z-Scores dos dados, seguindo a função $z = \frac{x - \mu}{\sigma}$, onde $\mu$ é a média do conjunto de dados e $\sigma$ é o desvio padrão do mesmo (arredonde os valores para 4 casas decimais).

In [ ]:
def z_score(data:list[float]) -> np.array:
  '''
  Recebe uma lista numérica e retorna uma lista
  com os valores da lista original com a filtro
  zscore.
  '''
  # Converte para um array
  data = np.array(data)
  # Cálculo da média
  media = data.mean()
  # Cálculo do desvio padrão
  std = data.std()
  # Conversão para z-score
  z_score_data = (data-media)/std
  # Arredonda os valores
  z_score_data = np.round(z_score_data, 4)

  return z_score_data

In [ ]:
# Exemplo 1
lista = [4, 6, 7, 8, 9]
#z_score = [-1.6275, -0.465, 0.1162, 0.6975, 1.2787]
z_score(lista)

array([-1.6275, -0.465 ,  0.1162,  0.6975,  1.2787])

In [ ]:
# Exemplo 2
lista = [33.1, 12.3, 15.2, 18.4, 77.9, 20.3, 19.5, 33.2, 45.7, 17.6]
#z_score = [0.1997, -0.8994, -0.7461, -0.577, 2.5671, -0.4766, -0.5189, 0.205, 0.8656, -0.6193]
z_score(lista)

array([ 0.1997, -0.8994, -0.7461, -0.577 ,  2.5671, -0.4766, -0.5189,
        0.205 ,  0.8656, -0.6193])

### 4) Escalonamento MinMaxScaler

De forma anáçoga a normalização, o MinMaxScaler altera a escala a ser utilizada em um conjunto de dados, onde busca-se os valores máximo e mínimo de um conjunto de dados para depois transformar em uma escala que varia entre esses valores. O objetivo deste exercício será desenvolver uma função chamada `minmaxscaler` que irá receber como entrada um conjunto de dados e de saída será uma lista com os valores na nova escala seguindo a função $y = \frac{x - min}{max - min}$ (arredonde para 4 casas decimais).

In [ ]:
def minmaxscaler(data:list[float]) -> np.array:
  '''
  Recebe uma lista numérica e retorna uma lista
  com os valores da lista original com a filtro
  minmaxscaler.
  '''
  # Converte a lista para um np.array
  data = np.array(data)
  # Calcula o mínimo e o máximo
  minimo = data.min()
  maximo = data.max()
  # Converte para minmaxscaler
  minmaxscaler_data = (data-minimo)/(maximo-minimo)
  # Arredonda com 4 casa decimais
  minmaxscaler_data = np.round(minmaxscaler_data, 4)

  return minmaxscaler_data

In [ ]:
# Exemplo 1
lista = [4, 6, 7, 8, 9]
#y_score = [0.0, 0.4, 0.6, 0.8, 1.0] # Resposta
print(minmaxscaler(lista))

[0.  0.4 0.6 0.8 1. ]


In [ ]:
# Exemplo 2
lista = [33.1, 12.3, 15.2, 18.4, 77.9, 20.3, 19.5, 33.2, 45.7, 17.6]
#y_score = [0.317, 0.0, 0.044, 0.093, 1.0, 0.122, 0.11, 0.319, 0.509, 0.081] # Resposta
print(minmaxscaler(lista))

[0.3171 0.     0.0442 0.093  1.     0.122  0.1098 0.3186 0.5091 0.0808]


### 5) Matching entre Vetores

No contexto de Machine Learning, um processo bem comum é de comparar respostas entre vetores para entender o quão acertivo foi um determinado modelo. Dado um contexto, desenvolva a função `vector_matching` que verifica posição a posição destes vetores, que valores de zeros e uns foram acertados. Para esta função têm-se como entrada __dois vetores de dimensões iguais__ preenchidos com 0 ou 1 e a saída da função será o percentual de acerto entre os vetores (arredonde o percentual para 1 casa decimal).

In [ ]:
def vector_matching(v1:list[int], v2:list[int]) -> float:
  '''
  Recebe duas listas e retorna a proporção em
  que os valores das duas listas são iguais.
  '''
  # Converte as listas para np.array
  v1 = np.array(v1)
  v2 = np.array(v2)
  # Cria uma máscara que compara os arrays
  mask = v1 == v2
  # Cria um array de zeros calcular os acertos
  acertos = np.zeros(mask.shape[0])
  # Adiciona 1 para onde foi igual
  acertos[mask] = 1
  # Calcula a proporção de acertos, dividindo
  # o total de uns pelo tamanho do array
  prop = acertos.sum()/acertos.shape[0]
  # Arredonda a proporção
  prop = round(prop, 3)

  return prop

In [ ]:
#Exemplos
#Exemplo 1
v1 = [0, 0, 0, 1, 1, 1, 1, 0]
v2 = [1, 0, 0, 1, 1, 0, 0, 1]
# Resposta = 50.0%

prop = vector_matching(v1, v2)
print(f'{round(prop*100, 3)}%')

50.0%


In [ ]:
#Exemplo 2
v1 = [1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1]
v2 = [1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0]
# Resposta = 47.1%

prop = vector_matching(v1, v2)
print(f'{round(prop*100, 3)}%')

47.1%
